import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import React, { useState } from 'react'
import { Button, Col, Form, Row } from 'react-bootstrap'
import { toast } from 'react-toastify';
import axios from 'axios'
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] })

export default function Home () {
  const [formData, setFormData] = useState({ sUsername: '' });
  const router = useRouter();

  const handleChange = (e) => {
    const { name, value } = e.target
    setFormData({ ...formData, [name]: value });
  };

  const handleSubmit = async () => {
    if (formData.sUsername) {
      router.push({
        pathname: '/my-account',
        query: { data: formData.sUsername },
      });
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className='login'>
          <h1>Welcome</h1>

          <form className='mt-5'>
            <Row >
              <Form.Group className="mb-3 userinput" controlId="formBasicPassword">
                <Form.Label>Username</Form.Label>
                <Form.Control type="text" name='sUsername' onChange={(e) => handleChange(e)} placeholder="Enter Your gitHub Username" />
              </Form.Group>
            </Row>
          </form>
          <Button onClick={() => handleSubmit()} type="submit">Submit</Button>
        </div>

      </main>
    </>
  )
}
      // await axios.get(`${process.env.baseURL}users/${formData.sUsername}`)
      //   .then((res) => {
          // toast.success(`Welcome ${res.data.name}`, {
          //   position: "top-right",
          //   autoClose: 5000,
          //   hideProgressBar: false,
          //   closeOnClick: true,
          //   pauseOnHover: true,
          //   draggable: true,
          //   progress: undefined,
          //   theme: "colored",
          // })

      //     router.push({
      //       pathname: '/my-account',
      //       query: { data: formData.sUsername },
      //     });

      //   }).catch(() => {
          // toast.error('User Not Found', {
          //   position: "top-right",
          //   autoClose: 5000,
          //   hideProgressBar: false,
          //   closeOnClick: true,
          //   pauseOnHover: false,
          //   draggable: true,
          //   progress: undefined,
          //   theme: "colored",
          // });
      //   })
